version: "3.8"

services:
  web:
    build: .
    container_name: codeigniter_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ci_db
      - DB_USER=ci_user
      - DB_PASSWORD=ci_pass
    restart: always

  db:
    image: mysql/mysql-server:5.7
    container_name: codeigniter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ci_db
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

volumes:
  db_data:
